[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "keonyoung00", email = "202206544+keonyoung00@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ml-zoomcamp = "ml_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
